# Generated by Django 4.2.16 on 2026-04-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('tbd', 'TBD'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round-robin', 'Round Robin'), ('single-elimination', 'Single Elimination')], default='round-robin', max_length=50),
        ),
    ]
